.TH "" "" "" "" ""
.SH NAME
.PP
openstack\-juju \- Ubuntu OpenStack Installer documentation
.SH SYNOPSIS
.PP
usage: openstack\-juju [subcommand] [opts]
.PP
$ openstack\-juju deploy jenkins $ openstack\-juju deploy \-n 5
jenkins\-slave $ openstack\-juju add\-relation jenkins jenkins\-slave $
openstack\-juju set jenkins password=AseCreTPassWoRd $ openstack\-juju
expose jenkins
.SH DESCRIPTION
.PP
This is a wrapper around Juju to setup necessary requirements for
allowing a user to orchestrate services on top of OpenStack.
