.TH "" "" "" "" ""
.SH NAME
.PP
openstack\-status \- Ubuntu OpenStack Installer documentation
.SH SYNOPSIS
.PP
usage: \f[B]openstack\-status\f[] [\-h] [\-\-enable\-swift]
[\-\-placement]
.PP
optional arguments:
.IP
.nf
\f[C]
\-h,\ \-\-help\ \ \ \ \ \ show\ this\ help\ message\ and\ exit
\-\-enable\-swift\ \ Enable\ swift\ storage
\-\-placement\ \ \ \ \ Show\ machine\ placement\ UI\ before\ deploying
\f[]
.fi
.SH DESCRIPTION
.PP
Ubuntu OpenStack installer is a metal to cloud image that provides an
extremely simple way to install, deploy and scale an OpenStack cloud on
top of Ubuntu server.
Initial configurations are available for single physical system
deployments as well as multiple physical system deployments.
.PP
This is the user interface for managing the deployed cloud.
