#!/usr/bin/env python2.7
# -*- mode: python; -*-

"""Upload files to MAAS.

TODO: Remove once LP#1187826 is Fix Released.

This is a workaround while file uploads don't work via maas-cli; see
https://bugs.launchpad.net/maas/+bug/1187826 for details.
"""

import argparse
import urllib2

from MultipartPostHandler import MultipartPostHandler

from apiclient.maas_client import MAASOAuth

class HTTPMAASOAuthProcessor(urllib2.BaseHandler):

    def __init__(self, consumer_key, resource_token, resource_secret):
        self.auth = MAASOAuth(consumer_key, resource_token, resource_secret)

    def http_request(self, req):
        headers = {}
        self.auth.sign_request(req.get_full_url(), headers)
        for name, value in headers.iteritems():
            req.add_header(name, value)
        return req

parser = argparse.ArgumentParser(description="Upload file to MAAS")
parser.add_argument("url", metavar="URL", help="MAAS URL")
parser.add_argument("credentials", help="MAAS credentials")
parser.add_argument("name", help="Target file name")
parser.add_argument("file", help="File to upload")

args = parser.parse_args()

opener = urllib2.build_opener(MultipartPostHandler,
                              HTTPMAASOAuthProcessor(*args.credentials.split(":")))
params = {"filename": args.name, "file": open(args.file, "rb")}
opener.open(args.url + "/files/?op=add", params)
