#cloud-config

write_files:
  - content: |
      #!/bin/sh
      mkdir -p /dev/net || true
      mknod /dev/kvm c 10 232
      mknod /dev/net/tun c 10 200
      exit 0
    path: /etc/rc.local
    permissions: '0755'
packages:
  - software-properties-common
{% if extra_pkgs %}
{% for pkg in extra_pkgs %}
  - {{ pkg }}
{% endfor %}
{% endif %}
groups:
  - libvirtd: [ubuntu]
  - sudo: [ubuntu]
{% if http_proxy %}
apt_proxy: {{ http_proxy }}
{% endif %}
{% if https_proxy %}
apt_https_proxy: {{ https_proxy }}
{% endif %}
apt_get_wrapper:
  command: eatmydata
  enabled: auto
apt_sources:
  - source: deb http://ppa.launchpad.net/cloud-installer/testing/ubuntu $RELEASE main
    key: |
      -----BEGIN PGP PUBLIC KEY BLOCK-----
      Version: SKS 1.1.4
      Comment: Hostname: keyserver.ubuntu.com

      mI0EUwap0AEEAOcvGspxrV0/83Xa6grEAplHLuuvj3CrOH26XwSleu/wzzTmNqKDnZLWjBkA
      qdbfYzQ3T4aD2uWfMJ2doqemBmLZWKrkMInLcS2o3cqraFHJaZDAvJHg7wiDBYiuq0cCrj/m
      enC351p/DLQ+QuiHE1hgX6JV4nF527rCmGbWSSTRABEBAAG0KExhdW5jaHBhZCBQUEEgZm9y
      IFVidW50dSBDbG91ZCBJbnN0YWxsZXKIuAQTAQIAIgUCUwap0AIbAwYLCQgHAwIGFQgCCQoL
      BBYCAwECHgECF4AACgkQ3eaD+NL/Ce1RuQQApA4AaFlsujGJ4i2lN1qLbxivXu2fs+D9aXAV
      MgYINVj13/xxtn+1PqV7x7I9ej+Adhy9uLc+7T6mfx7Ahn791hbNr/gycSZEkvdp3gZRFWHS
      MqPZ3uOvWieRR347tMTh/BgxEsTdTUcLbt7jZkk6NypGO+ej8WtWugJ9kwOPb9s=
      =aDcI
      -----END PGP PUBLIC KEY BLOCK-----
{% if extra_ppa %}
{% for ppa in extra_ppa %}
  - source: "{{ ppa }}"
{% endfor %}
{% endif %}
{% if extra_sshkeys %}
ssh_authorized_keys:
{% for ssh in extra_sshkeys %}
  - {{ ssh }}
{% endfor %}
{% endif %}
random_seed:
  command: {{seed_command}}
{% if apt_mirror %}
apt_mirror: {{apt_mirror}}
{% endif %}
package_update: true
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True
manage_etc_hosts: localhost


# Make sure we load our modules on first creation
runcmd:
  - [ sh, /etc/rc.local ]
  - echo "export PATH=$PATH:/usr/sbin" >> /home/ubuntu/.bashrc
{% if http_proxy %}
  - echo "export http_proxy={{ http_proxy }}" >> /home/ubuntu/.bashrc
  - echo "export HTTP_PROXY={{ http_proxy }}" >> /home/ubuntu/.bashrc
{% endif %}
{% if https_proxy %}
  - echo "export https_proxy={{ https_proxy }}" >> /home/ubuntu/.bashrc
  - echo "export HTTPS_PROXY={{ https_proxy }}" >> /home/ubuntu/.bashrc
{% endif %}
