#!/usr/bin/env python3
# Usage:
# ~/packages/cloud-installer/share master python print-first-group '(foo)' foo
# foo
# ~/packages/cloud-installer/share master python print-first-group '(foo)' bar
#

import re
import sys

if len(sys.argv) == 3:
    g = re.match(sys.argv[1], sys.argv[2])
    if g:
        print(g.groups()[0])
