#!/usr/bin/env python3
# -*- mode: python; -*-
#
# cloud-status - Displays status of all managed nodes
#
# Copyright 2014 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This package is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Usage:
# ./re <function> <pattern> <stdin|fileobj>

import re
import sys


def print_version():
    """ Prints version string from debian/changelog

    @return: 0 on success 1 on failure
    """
    pattern = 'cloud-installer\s.(.*)-\dubuntu\d'
    with open('debian/changelog', 'r') as f:
        match = re.match(pattern, f.read())
    if match:
        print(match.groups()[0])
        return 0
    return 1

def validate_email_address(email):
    """ Validates and email address

    @param email: Email address in the form of name@domain.com
    @return: 0 on success 1 on failure
    """
    pattern = "[^@]+@[^@]+\.[^@]+"
    if not re.match(pattern, email):
        return 1
    return 0

if __name__ == "__main__":
    if len(sys.argv) >= 2:
        if "print_version" in sys.argv[1]:
            sys.exit(print_version())
        if "validate_email" in sys.argv[1]:
            sys.exit(validate_email_address(sys.argv[2]))
    else:
        sys.exit(1)
