#!/bin/bash

echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
echo Ubuntu Openstack Installer Uninstalling ...
echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
rm -rf /etc/cloud-installer || true
rm -rf ~/.cloud-install || true
lxc-stop -n uoi-bootstrap
lxc-destroy -n uoi-bootstrap
