#!/bin/bash

echo -n Ubuntu Openstack Installer Uninstalling ...

WHAT=$(openstack-install -g install_type)

if [ -f ~/.cloud-install/new-maas ]; then
  MAAS_TYPE=new
else
  MAAS_TYPE=existing
fi

apt_purge() {
  DEBIAN_FRONTEND=noninteractive apt-get -yy purge $@
}

CFG_HOME=$(openstack-install -g cfg_path)
case $WHAT in
  Multi)
    echo Multi install environment

    # FIXME: probably need to convert this to a python script to pull
    # same data from config object
    JUJU_HOME="$CFG_HOME/juju" juju destroy-environment --yes --force maas || exit 1

    if [ "$MAAS_TYPE" == "new" ]; then
        rm -r ~/.maascli.db

        whiptail --msgbox "MAAS packaging requires manual interaction.\nPlease answer YES to the questions in the next two screens." 15 30

        apt-get -y purge '.*maas.*'
        apt_purge 'bind9'
        sudo -u postgres psql -c 'drop database maasdb;'

        # Sometimes the twisted process just hangs with 100% cpu when uninstalling,
        # so we kill it explicitly.
        sudo killall -u maas twistd

        virsh destroy juju-bootstrap
        virsh undefine juju-bootstrap
        virsh vol-delete juju-bootstrap.qcow2
        virsh pool-refresh default

        # clean up the networking
        interface=$(cat /etc/openstack/interface)
        ifconfig br0 down
        brctl delbr br0
        if [ -n "$interface" ]; then
            ifdown $interface
        fi

        cp /etc/openstack/interfaces.cloud.bak /etc/network/interfaces
        cp -r /etc/openstack/interfaces.cloud.d.bak/* /etc/network/interfaces.d
        rm /etc/network/interfaces.d/openstack.cfg

        # iptables rule
        cp /etc/network/iptables.rules /etc/network/iptables.rules.bak
        rm /etc/network/iptables.rules

        if [ -n "$interface" ]; then
            ifup $interface
        fi
        ifdown lo && ifup lo
    fi

    # Multi places backup network settings here.
    rm -rf /etc/openstack || true

    ;;
  Single)
    echo Single install path.
    lxc-stop -n uoi-bootstrap || true
    lxc-destroy -n uoi-bootstrap || true
    container_ip=$(openstack-install -g container_ip)
    ip route del 10.0.4.0/24 via $container_ip dev lxcbr0 || true
    ;;
  *)
    echo Could not determine install type, was ~/.cloud-install removed prior to running the uninstallation?
    exit 1
    ;;
  esac


rm -rf ~/.cloud-install/juju || true
rm -f ~/.cloud-install/installed || true
