#!/bin/bash

echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
echo Ubuntu Openstack Installer Uninstalling ...
echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

if [ "$#" -eq 1 ] && [ $1 != '-u' ]; then
  WHAT=$1
elif [ "$#" -eq 2 ]; then
  WHAT=$2
elif [ -f ~/.cloud-install/multi ]; then
  WHAT=multi-system
elif [ -f ~/.cloud-install/single ]; then
  WHAT=single-system
elif [ -f ~/.cloud-install/landscape ]; then
  WHAT=multi-system
else
  echo "could not determine install type"
fi

if [ -f ~/.cloud-install/new-maas ]; then
  MAAS_TYPE=new
else
  MAAS_TYPE=existing
fi

apt_purge() {
  DEBIAN_FRONTEND=noninteractive apt-get -yy purge $@
}

case $WHAT in
  multi-system)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Multi install cleansing.
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

    juju destroy-environment --yes --force maas

    if [ "$MAAS_TYPE" == "new" ]; then
        rm -r ~/.maascli.db

        whiptail --msgbox "MAAS packaging requires manual interaction.\nPlease answer YES to the questions in the next two screens." 15 30

        apt-get -y purge '.*maas.*'
        apt_purge 'bind9'
        sudo -u postgres psql -c 'drop database maasdb;'

        # Sometimes the twisted process just hangs with 100% cpu when uninstalling,
        # so we kill it explicitly.
        sudo killall -u maas twistd

        virsh destroy juju-bootstrap
        virsh undefine juju-bootstrap
        virsh vol-delete juju-bootstrap.qcow2
        virsh pool-refresh default

        # clean up the networking
        interface=$(cat /etc/openstack/interface)
        ifconfig br0 down
        brctl delbr br0
        if [ -n "$interface" ]; then
            ifdown $interface
        fi

        cp /etc/openstack/interfaces.cloud.bak /etc/network/interfaces
        cp -r /etc/openstack/interfaces.cloud.d.bak/* /etc/network/interfaces.d
        rm /etc/network/interfaces.d/openstack.cfg

        # iptables rule
        cp /etc/network/iptables.rules /etc/network/iptables.rules.bak
        rm /etc/network/iptables.rules

        if [ -n "$interface" ]; then
            ifup $interface
        fi
        ifdown lo && ifup lo
    fi
    ;;
  single-system)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Single install cleansing.
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    lxc-stop -n uoi-bootstrap
    lxc-destroy -n uoi-bootstrap
    ;;
  *)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Please run with either single-system or multi-system as an argument.
    echo Example:
    echo   sudo openstack-install -u single-system
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    exit 1
    ;;
  esac


rm -rf ~/.cloud-install || true
rm -rf /etc/openstack || true
