#!/bin/bash

echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
echo Ubuntu Openstack Installer Uninstalling ...
echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

if [ "$#" -eq 1 ] && [ $1 != '-u' ]; then
  WHAT=$1
elif [ "$#" -eq 2 ]; then
  WHAT=$2
elif [ -f ~/.cloud-install/multi ]; then
  WHAT=multi-system
elif [ -f ~/.cloud-install/single ]; then
  WHAT=single-system
elif [ -f ~/.cloud-install/landscape ]; then
  WHAT=landscape-system
else
  echo "could not determine install type"
fi

apt_purge() {
  DEBIAN_FRONTEND=noninteractive apt-get -yy purge $@
}

case $WHAT in
  multi-system)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Multi install cleansing.
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

    # Here we shut down all the maas machines before doing a juju-destroy. We
    # do this because there might be more than one juju environment in the
    # maas (in fact, in the case of landscape it creates another for its
    # openstack environment), and we want to make sure to power off all the
    # machines.
    allocated=$(maas maas nodes list-allocated | \
      python3 -c 'import json; import sys; print(" ".join(map(lambda x: x["system_id"], json.load(sys.stdin))))')
    for system_id in $allocated; do
      maas maas node stop $system_id
    done

    juju destroy-environment --yes --force maas
    rm -r ~/.maascli.db

    apt_purge '.*maas.*'
    apt_purge 'bind9'
    sudo -u postgres psql -c 'drop database maasdb;'

    # Sometimes the twisted process just hangs with 100% cpu when uninstalling,
    # so we kill it explicitly.
    sudo killall -u maas twistd

    virsh destroy juju-bootstrap
    virsh undefine juju-bootstrap
    virsh vol-delete juju-bootstrap.qcow2
    virsh pool-refresh default

    # clean up the networking
    interface=$(cat /etc/openstack/interface)
    ifconfig br0 down
    brctl delbr br0
    if [ -n "$interface" ]; then
        ifdown $interface
    fi

    cp /etc/openstack/interfaces.cloud.bak /etc/network/interfaces
    cp -r /etc/openstack/interfaces.cloud.d.bak/* /etc/network/interfaces.d
    rm /etc/network/interfaces.d/openstack.cfg

    # iptables rule
    cp /etc/network/iptables.rules /etc/network/iptables.rules.bak
    rm /etc/network/iptables.rules

    if [ -n "$interface" ]; then
        ifup $interface
    fi
    ifdown lo && ifup lo
    ;;
  single-system)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Single install cleansing.
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    lxc-stop -n uoi-bootstrap
    lxc-destroy -n uoi-bootstrap
    ;;
  landscape-system)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Landscape installed system.
    echo
    echo Removing a Landscape environment is could potentionally be
    echo destructive. Therefore, it is recommended to uninstall
    echo the Landscape bits manually.
    echo
    echo Suggested Steps:
    echo
    echo First:
    echo $ sudo apt-get purge maas* openstack openstack-landscape
    echo
    echo You will want to deconfigure and purge the maas database
    echo when prompted.
    echo
    echo Second:
    echo $ mv ~/.cloud-install ~/.cloud-install-backup
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    exit 1
    ;;
  *)
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    echo Please run with either single-system or multi-system as an argument.
    echo Example:
    echo   sudo openstack-install -u single-system
    echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    exit 1
    ;;
  esac

# these may or may not be installed, so we list them all individually
apt_purge '.*juju.*'
apt_purge cloud-install-single
apt_purge cloud-install-multi
apt_purge cloud-install-landscape
apt_purge openstack
apt_purge openstack-single
apt_purge openstack-multi
apt_purge openstack-landscape


# Remove any extra packages that aren't needed after purging.
apt-get -yy autoremove

# just make sure juju-mongodb died. LP#1306315
MONGOD=$(pgrep mongod)
RET=$?
if [ ${RET} -eq 0 ]; then
  if [ ${MONGOD} -gt 0 ]; then
    kill -9 ${MONGOD}
  fi
fi

rm -rf /etc/openstack || true
